##### GENERAL PARAMETERS #####
exp_id: "train_ppo"         # Name for log files and checkpoints
agent: "AgentPPO"                # Agent: "PPO", "DDPG", "A3C"
train: False                 # Mode: Train or Test
resume: False               # Whether to Load Last Model for Further Training
save_model: True            
save_video: True
load_model: "model/5000_Episode_checkpoint_901120_SV3.model"              # Model to load for Testing
log_dir: ""
##############################

##### TRAINING PARAMETERS ######
num_episodes: 5000          # DEFAULT: 10000          
batch_size: 256             # DEFAULT: 64
num_epochs: 10              # DEFAULT: 10
lr: 0.0005                  # DEFAULT: 0.0005
lr_decay: True              # DEFAULT: False

log_freq: 20                # DEFAULT: 20
eval_freq: 1000             # DEFAULT: 100
min_reward: 50              # DEFAULT: 50
################################

##### ENVIRONMENT PARAMETERS #####
obs_dim: [2,18,18]          # DEFAULT: [2,18,18], Agent Observation Space
num_actions: 1              # DEFAULT: 1, Agent Action Space
all_random: False           # DEFAULT: False, Whether to Train on All Random Vehicles
spawn_vehicles: 3           # DEFAULT: 0, Number of Non-Agent Vehicles to Spawn, Set 0 to Disable
random_lane: False          # DEFAULT: False, Whether to Randomize Agent Spawn Lane
offroad_thresh: -1          # DEFAULT: -1, Number of Steps Agent is Allowed to Ride Offroad
random_obstacles: 0         # DEFAULT: 0, Number of Static Obstacles to Spawn (Unused)
##################################

####### PPO PARAMETERS ########
gae_lambda: 0.95
gae_gamma: 0.9
ppo_epsilon: 0.2
target_kl: None
ppo_memory_size: 2048
################################

####### DDPG PARAMETERS ########
ddpg_actor_lr: 0.001
ddpg_critic_lr: 0.002
ddpg_gamma: 0.99
ddpg_tau: 0.005
ddpg_best: True
################################

####### A3C PARAMETERS ########
a3c_gamma: 0.99             # DEFAULT: 0.99, Generalised Advantage Estimate Gamma
rmsprop_epsilon: 0.00001    # DEFAULT: 0.00001
update_global_freq: 500     # DEFAULT: 5
num_workers: -1             # DEFAULT: -1
actor_coeff: 1.0            # DEFAULT: 1.0
critic_coeff: 0.5           # DEFAULT: 0.5
entropy_coeff: 0.01         # DEFAULT:0.01
################################

###### NEURAL NETWORK PARAMS ######
arch: "Identity"            # "DoubleConv","NatureCnn","ConvLSTM","MLP","Identity"
fc_layers: 2                # DEFAULT: 2
fc_width: 256               # DEFAULT: 256
###################################